# ItemBlind Build Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Environment & Dependencies
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.158.0+26.2

# Mod Information
mod_version=1.0.0
modmenu_version=20.0.1
cloth_config_version=26.2.155
maven_group=com.itemblind
archives_base_name=itemblind
